apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../observability
  - airflow.yaml

images:
  - name: detectra-api
    newName: ghcr.io/njchathura-boop/bot-review-campaign-api
    newTag: latest
  - name: detectra-jobs
    newName: ghcr.io/njchathura-boop/bot-review-campaign-jobs
    newTag: latest
  - name: detectra-airflow
    newName: ghcr.io/njchathura-boop/bot-review-campaign-airflow
    newTag: latest
