apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bot-review-campaign
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/njchathura-boop/Bot-Review-Campaign.git
    targetRevision: main
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: bot-campaign
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
