apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bot-campaign
resources:
  - stack.yaml
configMapGenerator:
  - name: detectra-spark-code
    files:
      - review_stream.py=../../spark/review_stream.py
generatorOptions:
  disableNameSuffixHash: true
